In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("D:/Dixant/CDAC/Machine Learning/LAB GRADED/creditcard.csv")

In [3]:
data.head(10)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   
5   2.0 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728  0.476201   
6   4.0  1.229658  0.141004  0.045371  1.202613  0.191881  0.272708 -0.005159   
7   7.0 -0.644269  1.417964  1.074380 -0.492199  0.948934  0.428118  1.120631   
8   7.0 -0.894286  0.286157 -0.113192 -0.271526  2.669599  3.721818  0.370145   
9   9.0 -0.338262  1.119593  1.044367 -0.222187  0.499361 -0.246761  0.651583   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   
5  0.260314 -0.568671  ... -0.208254 -0.559825 -0.026398 -0.371427 -0.232794   
6  0.081213  0.464960  ... -0.167716 -0.270710 -0.154104 -0.780055  0.750137   
7 -3.807864  0.615375  ...  1.943465 -1.015455  0.057504 -0.649709 -0.415267   
8  0.851084 -0.392048  ... -0.073425 -0.268092 -0.204233  1.011592  0.373205   
9  0.069539 -0.736727  ... -0.246914 -0.633753 -0.120794 -0.385050 -0.069733   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  
5  0.105915  0.253844  0.081080    3.67      0  
6 -0.257237  0.034507  0.005168    4.99      0  
7 -0.051634 -1.206921 -1.085339   40.80      0  
8 -0.384157  0.011747  0.142404   93.20      0  
9  0.094199  0.246219  0.083076    3.68      0  

[10 rows x 31 columns]

In [4]:
data=data.drop(['Amount'],axis=1)

In [5]:
data=data.drop(['Time'],axis=1)

In [6]:
data.shape

(284807, 29)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 29 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   V1      284807 non-null  float64
 1   V2      284807 non-null  float64
 2   V3      284807 non-null  float64
 3   V4      284807 non-null  float64
 4   V5      284807 non-null  float64
 5   V6      284807 non-null  float64
 6   V7      284807 non-null  float64
 7   V8      284807 non-null  float64
 8   V9      284807 non-null  float64
 9   V10     284807 non-null  float64
 10  V11     284807 non-null  float64
 11  V12     284807 non-null  float64
 12  V13     284807 non-null  float64
 13  V14     284807 non-null  float64
 14  V15     284807 non-null  float64
 15  V16     284807 non-null  float64
 16  V17     284807 non-null  float64
 17  V18     284807 non-null  float64
 18  V19     284807 non-null  float64
 19  V20     284807 non-null  float64
 20  V21     284807 non-null  float64
 21  V22     28

In [8]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [9]:
print(data.groupby('Class').size())

Class
0    284315
1       492
dtype: int64


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.30,stratify=data['Class'],random_state=42)

# KNN

In [11]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [12]:
y_pred = classifier.predict(X_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = accuracy_score(y_test,y_pred)
print("Accuracy:",result1)

Confusion Matrix:
[[85284    11]
 [   39   109]]
Accuracy: 0.9994148145547324


In [14]:
result2 = classification_report(y_test,y_pred,digits=4)
print("Classification Report:",)
print (result2)

Classification Report:
              precision    recall  f1-score   support

           0     0.9995    0.9999    0.9997     85295
           1     0.9083    0.7365    0.8134       148

    accuracy                         0.9994     85443
   macro avg     0.9539    0.8682    0.9066     85443
weighted avg     0.9994    0.9994    0.9994     85443



# SVC

In [15]:
from sklearn.svm import SVC

In [16]:
model=SVC(kernel='linear')

In [17]:
model.fit(X_train,y_train)

SVC(kernel='linear')

In [18]:
predicteddata=model.predict(X_test)
print(predicteddata)

[0 0 0 ... 0 0 0]


In [19]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result3 = confusion_matrix(y_test, predicteddata)
print("Confusion Matrix:")
print(result3)
result4 = accuracy_score(y_test,predicteddata)
print("Accuracy:",result4)

Confusion Matrix:
[[85267    28]
 [   39   109]]
Accuracy: 0.9992158515033414


In [20]:
result5 = classification_report(y_test,predicteddata,digits=4)
print("Classification Report:",)
print (result5)

Classification Report:
              precision    recall  f1-score   support

           0     0.9995    0.9997    0.9996     85295
           1     0.7956    0.7365    0.7649       148

    accuracy                         0.9992     85443
   macro avg     0.8976    0.8681    0.8823     85443
weighted avg     0.9992    0.9992    0.9992     85443



# Naive Bayes 

In [21]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [22]:
model.fit(X_train,y_train)

GaussianNB()

In [23]:
pred=model.predict(X_test)

In [24]:
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [25]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result6 = confusion_matrix(y_test, pred)
print("Confusion Matrix:")
print(result6)
result7 = accuracy_score(y_test,pred)
print("Accuracy:",result7)

Confusion Matrix:
[[83457  1838]
 [   29   119]]
Accuracy: 0.9781491754737076


In [26]:
result8 = classification_report(y_test,pred,digits=4)
print("Classification Report:",)
print (result8)

Classification Report:
              precision    recall  f1-score   support

           0     0.9997    0.9785    0.9889     85295
           1     0.0608    0.8041    0.1131       148

    accuracy                         0.9781     85443
   macro avg     0.5302    0.8913    0.5510     85443
weighted avg     0.9980    0.9781    0.9874     85443



# Decision Tree + Random Forest

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)

In [29]:
y_pred = clf.predict(X_test)

In [30]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result9 = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result9)
result10 = accuracy_score(y_test, y_pred)
print("Accuracy:",result10)

Confusion Matrix:
[[85260    35]
 [   38   110]]
Accuracy: 0.9991456292499094


In [31]:
result11 = classification_report(y_test,y_pred,digits=4)
print("Classification Report:",)
print (result11)

Classification Report:
              precision    recall  f1-score   support

           0     0.9996    0.9996    0.9996     85295
           1     0.7586    0.7432    0.7509       148

    accuracy                         0.9991     85443
   macro avg     0.8791    0.8714    0.8752     85443
weighted avg     0.9991    0.9991    0.9991     85443



In [32]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=20)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=20)

In [33]:
y_predicted = model.predict(X_test)

In [34]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result12 = confusion_matrix(y_test, y_predicted)
print("Confusion Matrix:")
print(result12)
result13 = accuracy_score(y_test, y_predicted)
print("Accuracy:",result13)

Confusion Matrix:
[[85288     7]
 [   37   111]]
Accuracy: 0.9994850368081645


In [35]:
result14 = classification_report(y_test,y_predicted,digits=4)
print("Classification Report:",)
print (result14)

Classification Report:
              precision    recall  f1-score   support

           0     0.9996    0.9999    0.9997     85295
           1     0.9407    0.7500    0.8346       148

    accuracy                         0.9995     85443
   macro avg     0.9701    0.8750    0.9172     85443
weighted avg     0.9995    0.9995    0.9995     85443



I'm using Random Forest Classifier algorithm as  my best model because it is having maximum precision and recall.And, it also have best f1 score(relation with both percision and recall).We are haping a lot of data which may cause overfitting and random forest works with small small chuncks of data and make decision tree with them.

In [36]:
list1=[20,30,40,50]

In [37]:
list2=['gini','entropy']

In [38]:
from sklearn.model_selection import GridSearchCV
param_grid = {'n_estimators' : list1,'criterion':list2}

In [40]:
gridsearch = GridSearchCV(model, param_grid,cv=4)

In [41]:
gridsearch.fit(X_train,y_train)

GridSearchCV(cv=4, estimator=RandomForestClassifier(n_estimators=20),
             param_grid={'criterion': ['gini', 'entropy'],
                         'n_estimators': [20, 30, 40, 50]})

In [42]:
gridsearch.best_params_

{'criterion': 'gini', 'n_estimators': 30}

In [43]:
gridsearch.best_score_

0.9995385325334564

In [44]:
model = RandomForestClassifier(n_estimators=30,criterion='entropy')

In [45]:
model.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=30)

In [46]:
y_predicted = model.predict(X_test)

In [47]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result15 = confusion_matrix(y_test, y_predicted)
print("Confusion Matrix:")
print(result15)
result16 = accuracy_score(y_test, y_predicted)
print("Accuracy:",result16)

Confusion Matrix:
[[85292     3]
 [   34   114]]
Accuracy: 0.9995669627705019


In [48]:
result17 = classification_report(y_test,y_predicted,digits=4)
print("Classification Report:",)
print (result17)

Classification Report:
              precision    recall  f1-score   support

           0     0.9996    1.0000    0.9998     85295
           1     0.9744    0.7703    0.8604       148

    accuracy                         0.9996     85443
   macro avg     0.9870    0.8851    0.9301     85443
weighted avg     0.9996    0.9996    0.9995     85443

