In [17]:
import numpy as np
import pandas as pd

In [18]:
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [19]:
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [20]:
dataset = pd.read_csv(path, names = headernames)
print(type(dataset))
dataset.head()

<class 'pandas.core.frame.DataFrame'>


sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [21]:
x = dataset.drop('Class',axis='columns')
y = dataset.Class

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [23]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [24]:
model.fit(X_train,y_train)

GaussianNB()

In [25]:
model.score(X_test,y_test)

0.9111111111111111

In [26]:
model.predict(X_test)

array(['Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor'],
      dtype='<U15')

In [27]:
model.predict_proba(X_test)

array([[1.00000000e+000, 2.86284579e-017, 1.17918863e-025],
       [1.75168613e-060, 9.99452599e-001, 5.47401183e-004],
       [1.00000000e+000, 3.22841449e-017, 7.53476457e-026],
       [4.27417676e-162, 1.06991294e-005, 9.99989301e-001],
       [1.00000000e+000, 1.08339543e-017, 4.43272957e-026],
       [6.66806484e-079, 8.94028069e-001, 1.05971931e-001],
       [1.07468132e-125, 1.44955471e-004, 9.99855045e-001],
       [4.59354986e-116, 1.29795245e-002, 9.87020475e-001],
       [1.59227238e-096, 3.47999724e-001, 6.52000276e-001],
       [2.96153159e-172, 1.38544347e-007, 9.99999861e-001],
       [1.00000000e+000, 4.35612439e-017, 2.88247707e-025],
       [4.20864762e-170, 1.27875627e-009, 9.99999999e-001],
       [1.23629402e-067, 9.92659624e-001, 7.34037551e-003],
       [8.17570346e-076, 9.96216218e-001, 3.78378229e-003],
       [1.00000000e+000, 1.40133342e-017, 1.64144225e-025],
       [3.14129518e-089, 4.61119780e-001, 5.38880220e-001],
       [1.00000000e+000, 1.47970567e-016

In [28]:
from sklearn.model_selection import cross_val_score
a=cross_val_score(GaussianNB(),X_train, y_train, cv=5)
print(a)

[0.95238095 0.95238095 0.95238095 1.         0.95238095]


In [29]:
np.mean(a)

0.9619047619047618

# Scaling

In [30]:
from sklearn.preprocessing import StandardScaler

In [32]:
scaler = StandardScaler()
scaled = scaler.fit_transform(x)
b=np.array(scaled)

# VIF

In [33]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif['Features'] = x.columns
vif['VIF'] = [variance_inflation_factor(b, i) for i in range(b.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif


Features    VIF
2  petal-length  31.40
3   petal-width  16.14
0  sepal-length   7.10
1   sepal-width   2.10

In [34]:
x1 = dataset.drop(['Class','petal-length','petal-width'],axis='columns')
y1 = dataset.Class

In [35]:
x1

sepal-length  sepal-width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x1,y1,test_size=0.3)

In [37]:
model.fit(X_train,y_train)

GaussianNB()

In [38]:
model.score(X_test,y_test)

0.8222222222222222

In [39]:
model.predict(X_test)

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa'], dtype='<U15')

In [40]:
model.predict_proba(X_test)

array([[8.63967394e-02, 6.31614530e-01, 2.81988731e-01],
       [3.62300063e-01, 4.65728956e-01, 1.71970981e-01],
       [1.35949457e-03, 5.68049439e-01, 4.30591067e-01],
       [8.40832992e-01, 1.11257198e-01, 4.79098106e-02],
       [3.37745268e-05, 9.64326931e-02, 9.03533532e-01],
       [9.55116562e-01, 1.63314433e-02, 2.85519947e-02],
       [1.59357022e-05, 1.63773617e-01, 8.36210447e-01],
       [1.22582491e-06, 8.74863720e-02, 9.12512402e-01],
       [5.90758066e-02, 8.15770248e-01, 1.25153945e-01],
       [9.51782462e-01, 2.64205801e-02, 2.17969577e-02],
       [9.21410745e-01, 4.62599396e-02, 3.23293154e-02],
       [9.65805122e-01, 1.46033132e-02, 1.95915648e-02],
       [1.35536003e-02, 7.93249177e-01, 1.93197223e-01],
       [1.35536003e-02, 7.93249177e-01, 1.93197223e-01],
       [3.78792372e-02, 7.56466804e-01, 2.05653959e-01],
       [1.09215448e-04, 3.24209819e-01, 6.75680965e-01],
       [1.22582491e-06, 8.74863720e-02, 9.12512402e-01],
       [4.33016072e-07, 4.60259

In [41]:
from sklearn.model_selection import cross_val_score
a=cross_val_score(GaussianNB(),X_train, y_train, cv=5)
print(a)

[0.66666667 0.85714286 0.71428571 0.76190476 0.76190476]


In [42]:
np.mean(a)

0.7523809523809524