In [1]:
import numpy as np
import pandas as pd

In [4]:
diabetes = pd.read_csv("D:/Dixant/CDAC/Machine Learning/16-12-21/diabetes.csv")

In [5]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
diabetes['Insulin']=diabetes['Insulin'].replace(0,np.NaN)
diabetes['SkinThickness']=diabetes['SkinThickness'].replace(0,np.NaN)
diabetes['BloodPressure']=diabetes['BloodPressure'].replace(0,np.NaN)
diabetes['BMI']=diabetes['BMI'].replace(0.0,np.NaN)

In [7]:
diabetes['Insulin']=diabetes['Insulin'].replace(np.NaN,diabetes['Insulin'].mean())
diabetes['SkinThickness']=diabetes['SkinThickness'].replace(np.NaN,diabetes['SkinThickness'].mean())
diabetes['BloodPressure']=diabetes['BloodPressure'].replace(np.NaN,diabetes['BloodPressure'].mean())
diabetes['BMI']=diabetes['BMI'].replace(np.NaN,diabetes['BMI'].mean())

In [8]:
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0            6      148           72.0       35.00000  155.548223  33.6   
1            1       85           66.0       29.00000  155.548223  26.6   
2            8      183           64.0       29.15342  155.548223  23.3   
3            1       89           66.0       23.00000   94.000000  28.1   
4            0      137           40.0       35.00000  168.000000  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [10]:
x = diabetes.iloc[:, :-1].values
y = diabetes.iloc[:, -1].values

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [12]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [13]:
model.fit(X_train,y_train)

GaussianNB()

In [14]:
model.score(X_test,y_test)

0.7662337662337663

In [15]:
model.predict(X_test)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1], dtype=int64)

In [16]:
model.predict_proba(X_test)

array([[9.32637815e-01, 6.73621853e-02],
       [9.68668750e-01, 3.13312504e-02],
       [9.79846446e-01, 2.01535537e-02],
       [8.72647826e-01, 1.27352174e-01],
       [3.42931642e-01, 6.57068358e-01],
       [9.98555687e-01, 1.44431320e-03],
       [9.46955971e-01, 5.30440289e-02],
       [9.17661426e-01, 8.23385745e-02],
       [9.95536467e-01, 4.46353292e-03],
       [8.66149642e-01, 1.33850358e-01],
       [5.39920941e-01, 4.60079059e-01],
       [8.86690624e-01, 1.13309376e-01],
       [9.92094990e-01, 7.90501014e-03],
       [3.35186825e-01, 6.64813175e-01],
       [6.47198124e-02, 9.35280188e-01],
       [5.58908568e-02, 9.44109143e-01],
       [1.31659396e-01, 8.68340604e-01],
       [9.40701641e-01, 5.92983587e-02],
       [8.67561378e-01, 1.32438622e-01],
       [1.34401202e-01, 8.65598798e-01],
       [9.68245888e-01, 3.17541118e-02],
       [9.78130980e-01, 2.18690196e-02],
       [7.66715306e-01, 2.33284694e-01],
       [9.44704964e-01, 5.52950362e-02],
       [9.894439

In [17]:
from sklearn.model_selection import cross_val_score
a=cross_val_score(GaussianNB(),X_train, y_train, cv=5)
print(a)

[0.74074074 0.66666667 0.78504673 0.75700935 0.74766355]


In [18]:
np.mean(a)

0.7394254067151265

In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
scaler = StandardScaler()
scaled = scaler.fit_transform(x)
b=np.array(scaled)

In [28]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif = pd.DataFrame()
vif['Features'] = diabetes.columns[:8]
vif['VIF'] = [variance_inflation_factor(b, i) for i in range(b.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

Features   VIF
7                       Age  1.62
5                       BMI  1.56
3             SkinThickness  1.45
0               Pregnancies  1.43
1                   Glucose  1.33
2             BloodPressure  1.24
4                   Insulin  1.22
6  DiabetesPedigreeFunction  1.05

All the vif are around 1 so there is not much multicollinearity between the features.