In [2]:
import numpy as np

In [3]:
# Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
list1=[]
for i in range(len(arr)):
    if arr[i]%2!=0:
        list1.append(arr[i])
np.array(list1)

array([1, 3, 5, 7, 9])

In [14]:
# Replace items that satisfy a condition without affecting the original array?

arr= [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr1=[]
for i in range(len(arr)):
    if arr[i]%2!=0:
        arr1.append(-1)
    else:
        arr1.append(arr[i])
np.array(arr1)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [16]:
#How to stack two arrays vertically?

a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
print("----------SeriesA---------")
print(a)
print("----------SeriesB---------")
print(b)
print("----------Concatenated---------")
np.concatenate([a,b],axis=0)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
# How to get the positions where elements of two arrays match?
a=np.array([1,2,3,4,5,9])
b=np.array([2,2,7,8,9,9])
np.where(a==b)


(array([1, 5], dtype=int64),)

In [37]:
# How to reverse the rows of a 2D array?

arr=np.array([[0,1,2,3],
             [1,2,3,4],
             [2,3,4,5]])
flipped_arr = np.flip(arr)
print("orignal array")
print(arr)

print("FLIPPED ARRAY")
print(flipped_arr)

print("TRANSPOSE")
arr.T

orignal array
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]
FLIPPED ARRAY
[[5 4 3 2]
 [4 3 2 1]
 [3 2 1 0]]
TRANSPOSE


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [32]:
a=arr[::-1]
print(a)

[[2 3 4 5]
 [1 2 3 4]
 [0 1 2 3]]


In [38]:
arr=np.arange(10,34).reshape(8,3)

In [42]:
print("Creating 8X3 array using numpy.arange")
print(arr)
print("Dividing 8X3 array into 4 sub array")
np.split(arr,4)

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]
Dividing 8X3 array into 4 sub array


[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

# PANDAS QUESTIONS

In [45]:
#1.	How to import pandas and check the version?
import pandas as pd
pd.__version__

'1.1.3'

In [80]:
#How to create a series from a list, numpy array and dict?
list1=[1,2,3,4,55,6,57,48,39,13]
arr=np.array(list1)
dic={'one':[1,2,3,4],'two':[4,5,6,7]}
ser1=pd.Series(list1)
ser2=pd.Series(arr)
ser3=pd.Series(dic)

In [81]:
print("-----------Series1---------")
print(ser1)
print("-----------Series2---------")
print(ser2)
print("-----------Series3---------")
print(ser3)

-----------Series1---------
0     1
1     2
2     3
3     4
4    55
5     6
6    57
7    48
8    39
9    13
dtype: int64
-----------Series2---------
0     1
1     2
2     3
3     4
4    55
5     6
6    57
7    48
8    39
9    13
dtype: int32
-----------Series3---------
one    [1, 2, 3, 4]
two    [4, 5, 6, 7]
dtype: object


In [82]:
ser3=pd.Series(np.arange(10))


In [83]:
ser3

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [101]:
data=[ser1,ser2,ser3]
df=pd.DataFrame(data)
df=df.T
print(df)

    0   1  2
0   1   1  0
1   2   2  1
2   3   3  2
3   4   4  3
4  55  55  4
5   6   6  5
6  57  57  6
7  48  48  7
8  39  39  8
9  13  13  9


In [104]:
#How to assign name to the series ?
data=[ser1,ser2,ser3]
df=pd.DataFrame(data,index=["A","B","C"])
df=df.T
print(df)

    A   B  C
0   1   1  0
1   2   2  1
2   3   3  2
3   4   4  3
4  55  55  4
5   6   6  5
6  57  57  6
7  48  48  7
8  39  39  8
9  13  13  9


In [94]:
#How to get the items of series A not present in series B?

s1=pd.Series([1,2,3,4,5,6,7,8,9])
s2=pd.Series([11,12,13,14,5,6,7,8,9])
s1==s2

0    False
1    False
2    False
3    False
4     True
5     True
6     True
7     True
8     True
dtype: bool

In [96]:
s1[s1!=s2]

0    1
1    2
2    3
3    4
dtype: int64

In [105]:
#How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?
df.describe()

A        B         C
count  10.0000  10.0000  10.00000
mean   22.8000  22.8000   4.50000
std    23.8877  23.8877   3.02765
min     1.0000   1.0000   0.00000
25%     3.2500   3.2500   2.25000
50%     9.5000   9.5000   4.50000
75%    45.7500  45.7500   6.75000
max    57.0000  57.0000   9.00000

In [113]:
#How to get frequency counts of unique items of a series?
s=pd.Series([1,2,1,3,5,3,6,4,10,10])
s.value_counts()

10    2
3     2
1     2
6     1
5     1
4     1
2     1
dtype: int64

In [116]:
#How to convert the first character of each element in a series to uppercase?
s=pd.Series(['pandas','c++','c','prolog','lisp'])
s

0    pandas
1       c++
2         c
3    prolog
4      lisp
dtype: object

In [120]:
for i in range(len(s)):
    s[i]=s[i].title()
print(s)

0    Pandas
1       C++
2         C
3    Prolog
4      Lisp
dtype: object


0    Pandas
1       c++
2         c
3    prolog
4      lisp
dtype: object