In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("D:/Dixant/CDAC/Machine Learning/23-12-21/Admission_Prediction.csv")

In [3]:
dataset.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0           1      337.0        118.0                4.0  4.5  4.5  9.65   
1           2      324.0        107.0                4.0  4.0  4.5  8.87   
2           3        NaN        104.0                3.0  3.0  3.5  8.00   
3           4      322.0        110.0                3.0  3.5  2.5  8.67   
4           5      314.0        103.0                2.0  2.0  3.0  8.21   

   Research  Chance of Admit  
0         1             0.92  
1         1             0.76  
2         1             0.72  
3         1             0.80  
4         0             0.65

In [4]:
dataset.shape

(500, 9)

In [5]:
dataset=dataset.drop(['Serial No.'],axis=1)

In [6]:
dataset.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0      337.0        118.0                4.0  4.5  4.5  9.65         1   
1      324.0        107.0                4.0  4.0  4.5  8.87         1   
2        NaN        104.0                3.0  3.0  3.5  8.00         1   
3      322.0        110.0                3.0  3.5  2.5  8.67         1   
4      314.0        103.0                2.0  2.0  3.0  8.21         0   

   Chance of Admit  
0             0.92  
1             0.76  
2             0.72  
3             0.80  
4             0.65

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   GRE Score          485 non-null    float64
 1   TOEFL Score        490 non-null    float64
 2   University Rating  485 non-null    float64
 3   SOP                500 non-null    float64
 4   LOR                500 non-null    float64
 5   CGPA               500 non-null    float64
 6   Research           500 non-null    int64  
 7   Chance of Admit    500 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 31.4 KB


In [8]:
dataset.describe()

GRE Score  TOEFL Score  University Rating         SOP        LOR  \
count  485.000000   490.000000         485.000000  500.000000  500.00000   
mean   316.558763   107.187755           3.121649    3.374000    3.48400   
std     11.274704     6.112899           1.146160    0.991004    0.92545   
min    290.000000    92.000000           1.000000    1.000000    1.00000   
25%    308.000000   103.000000           2.000000    2.500000    3.00000   
50%    317.000000   107.000000           3.000000    3.500000    3.50000   
75%    325.000000   112.000000           4.000000    4.000000    4.00000   
max    340.000000   120.000000           5.000000    5.000000    5.00000   

             CGPA    Research  Chance of Admit  
count  500.000000  500.000000        500.00000  
mean     8.576440    0.560000          0.72174  
std      0.604813    0.496884          0.14114  
min      6.800000    0.000000          0.34000  
25%      8.127500    0.000000          0.63000  
50%      8.560000    1.000000          0.72000  
75%      9.040000    1.000000          0.82000  
max      9.920000    1.000000          0.97000

In [9]:
dataset['GRE Score']=dataset['GRE Score'].replace(np.NaN,dataset['GRE Score'].mean())
dataset['TOEFL Score']=dataset['TOEFL Score'].replace(np.NaN,dataset['TOEFL Score'].mean())
dataset['University Rating']=dataset['University Rating'].replace(np.NaN,dataset['University Rating'].mode()[0])

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   GRE Score          500 non-null    float64
 1   TOEFL Score        500 non-null    float64
 2   University Rating  500 non-null    float64
 3   SOP                500 non-null    float64
 4   LOR                500 non-null    float64
 5   CGPA               500 non-null    float64
 6   Research           500 non-null    int64  
 7   Chance of Admit    500 non-null    float64
dtypes: float64(7), int64(1)
memory usage: 31.4 KB


In [11]:
from sklearn.model_selection import train_test_split
data=dataset.iloc[:,:-1]
target=dataset.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(data,target,test_size=0.20,random_state=1)


In [12]:
from sklearn.svm import SVR
model=SVR(kernel='linear')
model

SVR(kernel='linear')

In [13]:
model.fit(x_train,y_train)

SVR(kernel='linear')

In [14]:
y_pred=model.predict(x_test)
y_pred

array([0.6244214 , 0.68874098, 0.92084515, 0.71219712, 0.79784286,
       0.68288408, 0.71349954, 0.68706517, 0.78092546, 0.65695639,
       0.66968512, 0.56677247, 0.74558323, 0.77498028, 0.75223439,
       0.8552863 , 0.61424133, 0.7417693 , 0.87349736, 0.64569721,
       0.58790558, 0.78302387, 0.80666146, 0.61778034, 0.77311714,
       0.56395582, 0.92457085, 0.63817281, 0.85253082, 0.7021113 ,
       0.61385879, 0.78681226, 0.585001  , 0.89728076, 0.49547408,
       0.78942041, 0.64035775, 0.61233041, 0.63761137, 0.8826372 ,
       0.54615759, 0.65221638, 0.75212006, 0.95714133, 0.75807032,
       0.48519862, 0.61389095, 0.60562065, 0.62801032, 0.64832042,
       0.81212746, 0.91504337, 0.85083759, 0.61484684, 0.72867208,
       0.63738709, 0.74007082, 0.59622118, 0.64755291, 0.69004991,
       0.40380499, 0.67768549, 0.72086786, 0.82064424, 0.96227558,
       0.61018365, 0.72618222, 0.75977951, 0.89804871, 0.68902799,
       0.58261675, 0.62591438, 0.80338521, 0.47682375, 0.91149

In [15]:
y_test

304    0.62
340    0.75
47     0.89
67     0.57
479    0.79
       ... 
11     0.84
192    0.86
92     0.34
221    0.75
110    0.61
Name: Chance of Admit, Length: 100, dtype: float64

In [16]:
import sklearn.metrics as metrics

In [17]:
mse = metrics.mean_squared_error(y_test,y_pred)
print("Mean Square Error ", mse)

Mean Square Error  0.0038180808186807046


In [18]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.8022846658028737

In [19]:
c =[ 0.01 , 0.1 , 1 ,3 , 7 , 10]
g = [0.001 , 0.01 , 0.1 , 1 , 10]

In [20]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C':c, 'gamma':g}

In [21]:
gridsearch = GridSearchCV(model, param_grid,cv=5)

In [22]:
gridsearch.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=SVR(kernel='linear'),
             param_grid={'C': [0.01, 0.1, 1, 3, 7, 10],
                         'gamma': [0.001, 0.01, 0.1, 1, 10]})

In [23]:
gridsearch.best_params_

{'C': 1, 'gamma': 0.001}

In [24]:
gridsearch.best_score_

0.76805280682079

In [25]:
model=SVR()
model

SVR()

In [26]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C':c, 'gamma':g}

In [27]:
gridsearch = GridSearchCV(model, param_grid,cv=5)

In [28]:
gridsearch.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [0.01, 0.1, 1, 3, 7, 10],
                         'gamma': [0.001, 0.01, 0.1, 1, 10]})

In [29]:
gridsearch.best_params_

{'C': 10, 'gamma': 0.001}

In [30]:
gridsearch.best_score_

0.7289217251324386

# PREDICTION

In [34]:
data = [[322.0, 107.0, 4.0,3.5,4.0,9.70,1]]
  
df = pd.DataFrame(data, columns =dataset.columns[:-1] )

df

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0      322.0        107.0                4.0  3.5  4.0   9.7         1

In [35]:
model.fit(x_train,y_train)

SVR()

In [36]:
pred=model.predict(df)
pred

array([0.74835709])

In [37]:
a=float(input("GRE Score : "))
b=float(input("TOFEL Score : "))
c=float(input("University Rating : "))
d=float(input("SOP : "))
e=float(input("LOR : "))
f=float(input("CGPA : "))
g=float(input("Research : "))

GRE Score : 322.0
TOFEL Score : 107.0
University Rating : 5.0
SOP : 3.5
LOR : 4.0
CGPA : 9.7
Research : 1


In [38]:
data = [[a, b, c, d,e,f,g]]
  
df = pd.DataFrame(data, columns =dataset.columns[:-1] )

df

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0      322.0        107.0                5.0  3.5  4.0   9.7       1.0

In [39]:
pred=model.predict(df)
pred

array([0.74971261])